working version

diff --git a/rebuild-rpm b/rebuild-rpm
--- a/rebuild-rpm
+++ b/rebuild-rpm
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+set -eo pipefail
+
 # --- for anaconda rpm rebuild ---
 # glib2-doc gtk3-devel-docs libarchive-devel libgnomekbd-devel
 # libtimezonemap-devel libxklavier-devel audit-libs-devel metacity gtk-doc
@@ -56,7 +58,7 @@ rpmdev-wipetree
 rpm -ihv src/rpms/base/anaconda/anaconda-33.25.4-6.4.el7.src.rpm
 cp -v src/rpms/base/anaconda/anaconda.spec ~/rpmbuild/SPECS/
 cp -v src/rpms/base/anaconda/0006-user-glade.patch ~/rpmbuild/SOURCES/
-rpmbuild -bb ~/rpmbuild/SPECS/anaconda.spec
+rpmbuild -bb ~/rpmbuild/SPECS/anaconda.spec #|| { echo -e "${RED}Build failed${NC}" ; exit 1; }
 cp -v ~/rpmbuild/RPMS/x86_64/anaconda-* src/rpms/
 
 echo -e "${GREEN}Rebuilding initial-setup rpm${NC}"
@@ -64,5 +66,5 @@ rpmdev-wipetree
 rpm -ihv src/rpms/base/initial/initial-setup-0.3.84-3.el7.src.rpm
 cp -v src/rpms/base/initial/initial-setup.spec ~/rpmbuild/SPECS/
 cp -v src/rpms/base/initial/0003-common-and-user.patch ~/rpmbuild/SOURCES/
-rpmbuild -bb ~/rpmbuild/SPECS/initial-setup.spec
+rpmbuild -bb ~/rpmbuild/SPECS/initial-setup.spec # || { echo -e "${RED}Build failed${NC}" ; exit 1; }
 cp -v ~/rpmbuild/RPMS/x86_64/initial* src/rpms/
